version: 0.2

phases:
  pre_build:
    commands:
      - git clone https://github.com/alan-keepaware/documentation-test.git
      - mkdir flattened
      - cp -R documentation-test/. flattened/
      - find ./flattened -type f  ! -name "*.md"  -delete
      - echo "Successful build"
  post_build:
    commands:
      - zip -r files.zip ~/flattened
      - echo "all in flattened"; ls flattened
      - find ./flattened -type f  ! -name "*.md"  -delete
      - echo "final flattened"; ls flattened
      ## - aws s3 cp archive.zip s3://your-s3-bucket/your-prefix/
artifacts:
  files:
    - '**/*'
