version: 0.2

phases:
  build:
    commands:
      - git clone https://github.com/alan-keepaware/documentation-test.git
      # - mkdir flattened
      # - cp -R documentation-test/. flattened/
      # - find ./flattened -type f  ! -name "*.md"  -delete
      # - echo "Successful build"

      - FILES=$(find . -name "*.md")

      # Flatten the file structure
      - mkdir flattened_files
      - IFS=$'\n' # Set Internal Field Separator to newline, or else the files might not be copied correctly
      - for FILE in $FILES; do cp $FILE flattened_files/; done

  post_build:
    commands:
      # Archive the .md files or prepare them for upload
      # - zip -r files.zip flattened_files
      - echo "Flattened files to upload:"; ls flattened_files

      # AWS S3 Upload
      - aws s3 cp flattened_files s3://myawsbucket123123123123123/docs/ --recursive