version: 0.2

phases:
  build:
    commands:
      # Identify and retrieve all .md files in the repository
      - FILES=$(find . -name "*.md")

      # Flatten the file structure
      - mkdir flattened_files
      - IFS=$'\n' # Set Internal Field Separator to newline
      - for FILE in $FILES; do cp $FILE flattened_files/; done

  post_build:
    commands:
      # Archive the .md files or prepare them for upload
      - zip -r files.zip flattened_files
      - echo "final flattened"; ls flattened_files

      # AWS S3 Upload
      # - aws s3 cp files.zip s3://your-s3-bucket/your-prefix/