name: Update Documentation

on:
  push:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set commit changes, excluding deleted files
      run: |
        changes=$(git diff --name-only -r HEAD^1 HEAD)
        deleted_files=$(git diff --diff-filter=D --name-only HEAD^1 HEAD)
        changed_files=$(comm -23 <(echo "$changes" | sort) <(echo "$deleted_files" | sort))

        # Write changes to a file
        echo "$changed_files" > changed-files.txt
        # Set the file path as an output variable
        echo "CHANGED_FILES_PATH=$(pwd)/changed-files.txt" >> $GITHUB_ENV

    # - name: Log Results
    #   run: echo "$CHANGED_FILES_PATH" >> distributedPatterns.log

    # # Logs files to be run as dis
    # - name: Upload Log File as Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: distributed-patterns
    #     path: distributedPatterns.log
    #

    - name: Get access token
      run: |
        response=$(curl -s -X POST \
          --header 'Content-Type: application/json' \
          -d '{"client_id":"7dti32o0619c5skd4i1m1d9337", "client_secret":"'"${{ secrets.CONSOLE_API_KEY }}"'"}' \
          'https://cloud.awarefilter.com/v1/oauth/token')
        echo "$response"
        # access_token=$(echo "$response" | jq -r .access_token)
        # echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: node distributePatterns.js
