name: Update Documentation

on:
  push:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONSOLE_API_KEY: ${{ secrets.CONSOLE_API_KEY }}
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set commit changes
      run: |
        changes=$(git diff --name-only -r HEAD^1 HEAD)
        deleted_files=$(git diff --diff-filter=D --name-only HEAD^1 HEAD)
        changed_files=$(comm -23 <(echo "$changed_files" | sort) <(echo "$deleted_files" | sort))
        # Write changes to a file
        echo "$changed_files" > changed-files.txt
        # Set the file path as an output variable
        echo "CHANGED_FILES_PATH=$(pwd)/changed-files.txt" >> $GITHUB_ENV
    - name: Get message
      run: |
        echo "CHANGED_FILES_PATH=${{ steps.set-changes.outputs.CHANGED_FILES_PATH }}";
        echo "$CHANGED_FILES_PATH";
        echo "$GITHUB_ENV"
        
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: node distributePatterns.js