name: Update Documentation

on:
  push:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONSOLE_API_KEY: ${{ secrets.CONSOLE_API_KEY }}
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set commit changes
      run: |
        changes=$(git diff --name-only -r HEAD^1 HEAD)
        # Write changes to a file
        echo "$changes" > changed-files.txt
        # Set the file path as an output variable
        echo "CHANGED_FILES_PATH=$(pwd)/changed-files.txt" >> $GITHUB_ENV
    - name: Get message
      run: echo "CHANGED_FILES_PATH=${{ steps.set-changes.outputs.CHANGED_FILES_PATH }}"
        
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: node distributePatterns.js