name: Update Documentation

on:
  push:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONSOLE_API_KEY: ${{ secrets.CONSOLE_API_KEY }}
      
    outputs:
      commit-changes: ${{ steps.set-changes.outputs.commit-changes }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set commit changes
      run: echo "GITHUB_SHA_SHORT=$(git diff --name-only -r HEAD^1 HEAD)" >> $GITHUB_ENV
    - name: Get message
      run: echo $GITHUB_SHA_SHORT
        
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: node distributePatterns.js